/** @file ctype_data.gen.h
 * Auto-generated by scripts/gen_ctype.py from UnicodeData.txt, PropList.txt -- do not edit. */
#ifndef CTYPE_DATA_GEN_H
#define CTYPE_DATA_GEN_H

#include <stdint.h>
#include <uchar.h>

/** @name Unicode character-property tables
 *  @{ */

/** Character-property flags stored per codepoint. */
enum uctype_flag {
	UCTYPE_ALPHA = 1u << 0,
	UCTYPE_DIGIT = 1u << 1,
	UCTYPE_LOWER = 1u << 2,
	UCTYPE_UPPER = 1u << 3,
	UCTYPE_SPACE = 1u << 4,
	UCTYPE_CNTRL = 1u << 5,
	UCTYPE_PRINT = 1u << 6,
	UCTYPE_BLANK = 1u << 7,
};

/** Codepoints per second-stage block (2^UCTYPE_BLOCK_BITS). */
#define UCTYPE_BLOCK_BITS 8

/** First-stage block index, addressed by (cp >> UCTYPE_BLOCK_BITS). */
extern const uint16_t uctype_stage1[4352];

/** Second-stage property blocks; see strings/ctype.h for the lookup. */
extern const uint8_t uctype_stage2[35584];

/** One simple case mapping; cp maps to lower/upper (itself if uncased). */
struct uctype_case_entry {
	char32_t cp;
	char32_t lower;
	char32_t upper;
};

/** Codepoints with a simple case mapping, sorted by cp for bsearch. */
extern const struct uctype_case_entry uctype_case_table[2799];

/** @} */

#endif /* CTYPE_DATA_GEN_H */
