/** @file conf_schema.gen.c
 * Auto-generated by scripts/gen_schema.py from conf_schema.json -- do not edit. */
#include "conf_schema.gen.h"

#include "codec/json.h"

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>

/** @name Key tables
 *  @{ */

/* --- json_conf --- */
typedef struct { const char *name; size_t len; int idx; } json_lookup_conf_entry_;
static const json_lookup_conf_entry_ json_lookup_conf_keys_[] = {
	{"kcp", 3, 2},
	{"log", 3, 8},
	{"psk", 3, 14},
	{"tcp", 3, 17},
	{"udp", 3, 20},
	{"obfs", 4, 12},
	{"user", 4, 21},
	{"linger", 6, 6},
	{"listen", 6, 7},
	{"method", 6, 10},
	{"netdev", 6, 11},
	{"connect", 7, 0},
	{"timeout", 7, 19},
	{"kcp_bind", 8, 3},
	{"loglevel", 8, 9},
	{"password", 8, 13},
	{"keepalive", 9, 5},
	{"time_wait", 9, 18},
	{"service_id", 10, 16},
	{"http_listen", 11, 1},
	{"kcp_connect", 11, 4},
	{"rendezvous_server", 17, 15},
};
static int json_lookup_conf_cmp_(const void *key_, const void *entry_)
{
	const json_lookup_conf_entry_ *k_ = (const json_lookup_conf_entry_ *)key_;
	const json_lookup_conf_entry_ *e_ = (const json_lookup_conf_entry_ *)entry_;
	if (k_->len < e_->len) { return -1; }
	if (k_->len > e_->len) { return  1; }
	return memcmp(k_->name, e_->name, k_->len);
}
static int
json_lookup_conf(const char *str, size_t len)
{
	const json_lookup_conf_entry_ key_ = {str, len, 0};
	const json_lookup_conf_entry_ *e_ =
		bsearch(&key_, json_lookup_conf_keys_, 22, sizeof(*json_lookup_conf_keys_), json_lookup_conf_cmp_);
	return e_ ? e_->idx : -1;
}

/* --- json_conf_kcp --- */
typedef struct { const char *name; size_t len; int idx; } json_lookup_conf_kcp_entry_;
static const json_lookup_conf_kcp_entry_ json_lookup_conf_kcp_keys_[] = {
	{"nc", 2, 3},
	{"mtu", 3, 2},
	{"flush", 5, 0},
	{"rcvwnd", 6, 5},
	{"resend", 6, 6},
	{"sndwnd", 6, 7},
	{"nodelay", 7, 4},
	{"interval", 8, 1},
};
static int json_lookup_conf_kcp_cmp_(const void *key_, const void *entry_)
{
	const json_lookup_conf_kcp_entry_ *k_ = (const json_lookup_conf_kcp_entry_ *)key_;
	const json_lookup_conf_kcp_entry_ *e_ = (const json_lookup_conf_kcp_entry_ *)entry_;
	if (k_->len < e_->len) { return -1; }
	if (k_->len > e_->len) { return  1; }
	return memcmp(k_->name, e_->name, k_->len);
}
static int
json_lookup_conf_kcp(const char *str, size_t len)
{
	const json_lookup_conf_kcp_entry_ key_ = {str, len, 0};
	const json_lookup_conf_kcp_entry_ *e_ =
		bsearch(&key_, json_lookup_conf_kcp_keys_, 8, sizeof(*json_lookup_conf_kcp_keys_), json_lookup_conf_kcp_cmp_);
	return e_ ? e_->idx : -1;
}

/* --- json_conf_tcp --- */
typedef struct { const char *name; size_t len; int idx; } json_lookup_conf_tcp_entry_;
static const json_lookup_conf_tcp_entry_ json_lookup_conf_tcp_keys_[] = {
	{"rcvbuf", 6, 2},
	{"sndbuf", 6, 4},
	{"nodelay", 7, 1},
	{"keepalive", 9, 0},
	{"reuseport", 9, 3},
};
static int json_lookup_conf_tcp_cmp_(const void *key_, const void *entry_)
{
	const json_lookup_conf_tcp_entry_ *k_ = (const json_lookup_conf_tcp_entry_ *)key_;
	const json_lookup_conf_tcp_entry_ *e_ = (const json_lookup_conf_tcp_entry_ *)entry_;
	if (k_->len < e_->len) { return -1; }
	if (k_->len > e_->len) { return  1; }
	return memcmp(k_->name, e_->name, k_->len);
}
static int
json_lookup_conf_tcp(const char *str, size_t len)
{
	const json_lookup_conf_tcp_entry_ key_ = {str, len, 0};
	const json_lookup_conf_tcp_entry_ *e_ =
		bsearch(&key_, json_lookup_conf_tcp_keys_, 5, sizeof(*json_lookup_conf_tcp_keys_), json_lookup_conf_tcp_cmp_);
	return e_ ? e_->idx : -1;
}

/* --- json_conf_udp --- */
static int
json_lookup_conf_udp(const char *str, size_t len)
{
	if (len < 2) { return -1; }
	switch ((unsigned char)str[1]) {
	case 'c':
		return len == 6 && memcmp(str, "rcvbuf", 6) == 0 ? 0 : -1;
	case 'e':
		return len == 9 && memcmp(str, "reuseport", 9) == 0 ? 1 : -1;
	case 'n':
		return len == 6 && memcmp(str, "sndbuf", 6) == 0 ? 2 : -1;
	default: return -1;
	}
}

/** @} */

/** @name Schema tables
 *  @{ */

static const struct json_constraint json_conf_udp_rcvbuf_c = {
	.flags = JSON_C_MAX,
	.u = { .max = UINTMAX_C(33554432) },
};
static const struct json_constraint json_conf_udp_sndbuf_c = {
	.flags = JSON_C_MAX,
	.u = { .max = UINTMAX_C(33554432) },
};
static const struct json_conf_udp json_conf_udp_defaults = {
	.reuseport = false,
};
static const struct json_field json_conf_udp_fields[] = {
	{ .name = "rcvbuf", .name_len = 6, .kind = JSON_K_UINT, .req_bit = -1, .offset = offsetof(struct json_conf_udp, rcvbuf), .constraint = &json_conf_udp_rcvbuf_c },
	{ .name = "reuseport", .name_len = 9, .kind = JSON_K_BOOL, .req_bit = -1, .offset = offsetof(struct json_conf_udp, reuseport) },
	{ .name = "sndbuf", .name_len = 6, .kind = JSON_K_UINT, .req_bit = -1, .offset = offsetof(struct json_conf_udp, sndbuf), .constraint = &json_conf_udp_sndbuf_c },
};
static const struct json_schema json_conf_udp_schema = {
	.fields = json_conf_udp_fields,
	.n_fields = 3,
	.obj_size = sizeof(struct json_conf_udp),
	.lookup = json_lookup_conf_udp,
	.defaults = &json_conf_udp_defaults,
	.present_field = -1,
};

static const struct json_constraint json_conf_tcp_rcvbuf_c = {
	.flags = JSON_C_MAX,
	.u = { .max = UINTMAX_C(33554432) },
};
static const struct json_constraint json_conf_tcp_sndbuf_c = {
	.flags = JSON_C_MAX,
	.u = { .max = UINTMAX_C(33554432) },
};
static const struct json_conf_tcp json_conf_tcp_defaults = {
	.keepalive = false,
	.nodelay = true,
	.reuseport = false,
};
static const struct json_field json_conf_tcp_fields[] = {
	{ .name = "keepalive", .name_len = 9, .kind = JSON_K_BOOL, .req_bit = -1, .offset = offsetof(struct json_conf_tcp, keepalive) },
	{ .name = "nodelay", .name_len = 7, .kind = JSON_K_BOOL, .req_bit = -1, .offset = offsetof(struct json_conf_tcp, nodelay) },
	{ .name = "rcvbuf", .name_len = 6, .kind = JSON_K_UINT, .req_bit = -1, .offset = offsetof(struct json_conf_tcp, rcvbuf), .constraint = &json_conf_tcp_rcvbuf_c },
	{ .name = "reuseport", .name_len = 9, .kind = JSON_K_BOOL, .req_bit = -1, .offset = offsetof(struct json_conf_tcp, reuseport) },
	{ .name = "sndbuf", .name_len = 6, .kind = JSON_K_UINT, .req_bit = -1, .offset = offsetof(struct json_conf_tcp, sndbuf), .constraint = &json_conf_tcp_sndbuf_c },
};
static const struct json_schema json_conf_tcp_schema = {
	.fields = json_conf_tcp_fields,
	.n_fields = 5,
	.obj_size = sizeof(struct json_conf_tcp),
	.lookup = json_lookup_conf_tcp,
	.defaults = &json_conf_tcp_defaults,
	.present_field = -1,
};

static const struct json_constraint json_conf_kcp_flush_c = {
	.flags = JSON_C_MAX,
	.u = { .max = UINTMAX_C(2) },
};
static const struct json_constraint json_conf_kcp_interval_c = {
	.flags = JSON_C_MIN | JSON_C_MAX,
	.u = { .min = UINTMAX_C(10), .max = UINTMAX_C(500) },
};
static const struct json_constraint json_conf_kcp_mtu_c = {
	.flags = JSON_C_MIN | JSON_C_MAX,
	.u = { .min = UINTMAX_C(300), .max = UINTMAX_C(1500) },
};
static const struct json_constraint json_conf_kcp_nc_c = {
	.flags = JSON_C_MAX,
	.u = { .max = UINTMAX_C(1) },
};
static const struct json_constraint json_conf_kcp_nodelay_c = {
	.flags = JSON_C_MAX,
	.u = { .max = UINTMAX_C(2) },
};
static const struct json_constraint json_conf_kcp_rcvwnd_c = {
	.flags = JSON_C_MIN | JSON_C_MAX,
	.u = { .min = UINTMAX_C(16), .max = UINTMAX_C(65536) },
};
static const struct json_constraint json_conf_kcp_resend_c = {
	.flags = JSON_C_MAX,
	.u = { .max = UINTMAX_C(100) },
};
static const struct json_constraint json_conf_kcp_sndwnd_c = {
	.flags = JSON_C_MIN | JSON_C_MAX,
	.u = { .min = UINTMAX_C(16), .max = UINTMAX_C(65536) },
};
static const struct json_conf_kcp json_conf_kcp_defaults = {
	.flush = 1u,
	.interval = 100u,
	.mtu = 1400u,
	.nc = 1u,
	.nodelay = 1u,
	.rcvwnd = 256u,
	.resend = 0u,
	.sndwnd = 256u,
};
static const struct json_field json_conf_kcp_fields[] = {
	{ .name = "flush", .name_len = 5, .kind = JSON_K_UINT, .req_bit = -1, .offset = offsetof(struct json_conf_kcp, flush), .constraint = &json_conf_kcp_flush_c },
	{ .name = "interval", .name_len = 8, .kind = JSON_K_UINT, .req_bit = -1, .offset = offsetof(struct json_conf_kcp, interval), .constraint = &json_conf_kcp_interval_c },
	{ .name = "mtu", .name_len = 3, .kind = JSON_K_UINT, .req_bit = -1, .offset = offsetof(struct json_conf_kcp, mtu), .constraint = &json_conf_kcp_mtu_c },
	{ .name = "nc", .name_len = 2, .kind = JSON_K_UINT, .req_bit = -1, .offset = offsetof(struct json_conf_kcp, nc), .constraint = &json_conf_kcp_nc_c },
	{ .name = "nodelay", .name_len = 7, .kind = JSON_K_UINT, .req_bit = -1, .offset = offsetof(struct json_conf_kcp, nodelay), .constraint = &json_conf_kcp_nodelay_c },
	{ .name = "rcvwnd", .name_len = 6, .kind = JSON_K_UINT, .req_bit = -1, .offset = offsetof(struct json_conf_kcp, rcvwnd), .constraint = &json_conf_kcp_rcvwnd_c },
	{ .name = "resend", .name_len = 6, .kind = JSON_K_UINT, .req_bit = -1, .offset = offsetof(struct json_conf_kcp, resend), .constraint = &json_conf_kcp_resend_c },
	{ .name = "sndwnd", .name_len = 6, .kind = JSON_K_UINT, .req_bit = -1, .offset = offsetof(struct json_conf_kcp, sndwnd), .constraint = &json_conf_kcp_sndwnd_c },
};
static const struct json_schema json_conf_kcp_schema = {
	.fields = json_conf_kcp_fields,
	.n_fields = 8,
	.obj_size = sizeof(struct json_conf_kcp),
	.lookup = json_lookup_conf_kcp,
	.defaults = &json_conf_kcp_defaults,
	.present_field = -1,
};

static const struct json_constraint json_conf_keepalive_c = {
	.flags = JSON_C_MAX,
	.u = { .max = UINTMAX_C(600) },
};
static const struct json_constraint json_conf_linger_c = {
	.flags = JSON_C_MIN | JSON_C_MAX,
	.u = { .min = UINTMAX_C(5), .max = UINTMAX_C(600) },
};
static const struct json_constraint json_conf_loglevel_c = {
	.flags = JSON_C_MAX,
	.u = { .max = UINTMAX_C(8) },
};
static const struct json_constraint json_conf_time_wait_c = {
	.flags = JSON_C_MIN | JSON_C_MAX,
	.u = { .min = UINTMAX_C(5), .max = UINTMAX_C(3600) },
};
static const struct json_constraint json_conf_timeout_c = {
	.flags = JSON_C_MIN | JSON_C_MAX,
	.u = { .min = UINTMAX_C(60), .max = UINTMAX_C(86400) },
};
static const struct json_conf json_conf_defaults = {
	.kcp = {
		.flush = 1u,
		.interval = 100u,
		.mtu = 1400u,
		.nc = 1u,
		.nodelay = 1u,
		.rcvwnd = 256u,
		.resend = 0u,
		.sndwnd = 256u,
	},
	.keepalive = 25u,
	.linger = 30u,
	.loglevel = 4u,
	.tcp = {
		.keepalive = false,
		.nodelay = true,
		.reuseport = false,
	},
	.time_wait = 120u,
	.timeout = 600u,
	.udp = {
		.reuseport = false,
	},
};
static const struct json_field json_conf_fields[] = {
	{ .name = "connect", .name_len = 7, .kind = JSON_K_STRING, .req_bit = -1, .offset = offsetof(struct json_conf, connect) },
	{ .name = "http_listen", .name_len = 11, .kind = JSON_K_STRING, .req_bit = -1, .offset = offsetof(struct json_conf, http_listen) },
	{ .name = "kcp", .name_len = 3, .kind = JSON_K_OBJECT, .req_bit = -1, .offset = offsetof(struct json_conf, kcp), .child = &json_conf_kcp_schema },
	{ .name = "kcp_bind", .name_len = 8, .kind = JSON_K_STRING, .req_bit = -1, .offset = offsetof(struct json_conf, kcp_bind) },
	{ .name = "kcp_connect", .name_len = 11, .kind = JSON_K_STRING, .req_bit = -1, .offset = offsetof(struct json_conf, kcp_connect) },
	{ .name = "keepalive", .name_len = 9, .kind = JSON_K_UINT, .req_bit = -1, .offset = offsetof(struct json_conf, keepalive), .constraint = &json_conf_keepalive_c },
	{ .name = "linger", .name_len = 6, .kind = JSON_K_UINT, .req_bit = -1, .offset = offsetof(struct json_conf, linger), .constraint = &json_conf_linger_c },
	{ .name = "listen", .name_len = 6, .kind = JSON_K_STRING, .req_bit = -1, .offset = offsetof(struct json_conf, listen) },
	{ .name = "log", .name_len = 3, .kind = JSON_K_STRING, .req_bit = -1, .offset = offsetof(struct json_conf, log) },
	{ .name = "loglevel", .name_len = 8, .kind = JSON_K_UINT, .req_bit = -1, .offset = offsetof(struct json_conf, loglevel), .constraint = &json_conf_loglevel_c },
	{ .name = "method", .name_len = 6, .kind = JSON_K_STRING, .req_bit = -1, .offset = offsetof(struct json_conf, method) },
	{ .name = "netdev", .name_len = 6, .kind = JSON_K_STRING, .req_bit = -1, .offset = offsetof(struct json_conf, netdev) },
	{ .name = "obfs", .name_len = 4, .kind = JSON_K_STRING, .req_bit = -1, .offset = offsetof(struct json_conf, obfs) },
	{ .name = "password", .name_len = 8, .kind = JSON_K_STRING, .req_bit = -1, .offset = offsetof(struct json_conf, password) },
	{ .name = "psk", .name_len = 3, .kind = JSON_K_STRING, .req_bit = -1, .offset = offsetof(struct json_conf, psk) },
	{ .name = "rendezvous_server", .name_len = 17, .kind = JSON_K_STRING, .req_bit = -1, .offset = offsetof(struct json_conf, rendezvous_server) },
	{ .name = "service_id", .name_len = 10, .kind = JSON_K_STRING, .req_bit = -1, .offset = offsetof(struct json_conf, service_id) },
	{ .name = "tcp", .name_len = 3, .kind = JSON_K_OBJECT, .req_bit = -1, .offset = offsetof(struct json_conf, tcp), .child = &json_conf_tcp_schema },
	{ .name = "time_wait", .name_len = 9, .kind = JSON_K_UINT, .req_bit = -1, .offset = offsetof(struct json_conf, time_wait), .constraint = &json_conf_time_wait_c },
	{ .name = "timeout", .name_len = 7, .kind = JSON_K_UINT, .req_bit = -1, .offset = offsetof(struct json_conf, timeout), .constraint = &json_conf_timeout_c },
	{ .name = "udp", .name_len = 3, .kind = JSON_K_OBJECT, .req_bit = -1, .offset = offsetof(struct json_conf, udp), .child = &json_conf_udp_schema },
	{ .name = "user", .name_len = 4, .kind = JSON_K_STRING, .req_bit = -1, .offset = offsetof(struct json_conf, user) },
};
static const struct json_schema json_conf_schema = {
	.fields = json_conf_fields,
	.n_fields = 22,
	.obj_size = sizeof(struct json_conf),
	.lookup = json_lookup_conf,
	.defaults = &json_conf_defaults,
	.present_field = -1,
};

/** @} */

/** @name Codec functions
 *  @{ */

void json_free_conf(struct json_conf *obj)
{
	json_free(&json_conf_schema, obj);
}

bool json_unmarshal_conf(
	struct json_conf *obj, char *json, size_t length)
{
	return json_unmarshal(&json_conf_schema, obj, json, length);
}

/** @} */
