/** @file conf_schema.gen.c
 * Auto-generated by scripts/gen_schema.py from conf_schema.json -- do not edit. */
#include "conf_schema.gen.h"

#include "codec/json.h"

#include <stdlib.h>
#include <string.h>

/** @name Key tables
 *  @{ */

/* --- json_conf --- */
typedef struct {
	const char *name;
	size_t len;
	int idx;
} json_conf_entry_;
static const json_conf_entry_ json_conf_keys_[] = {
	{ "kcp", 3, 2 },
	{ "psk", 3, 13 },
	{ "tcp", 3, 16 },
	{ "udp", 3, 19 },
	{ "obfs", 4, 11 },
	{ "user", 4, 20 },
	{ "linger", 6, 6 },
	{ "listen", 6, 7 },
	{ "method", 6, 9 },
	{ "netdev", 6, 10 },
	{ "connect", 7, 0 },
	{ "timeout", 7, 18 },
	{ "kcp_bind", 8, 3 },
	{ "loglevel", 8, 8 },
	{ "password", 8, 12 },
	{ "keepalive", 9, 5 },
	{ "time_wait", 9, 17 },
	{ "service_id", 10, 15 },
	{ "http_listen", 11, 1 },
	{ "kcp_connect", 11, 4 },
	{ "rendezvous_server", 17, 14 },
};
static int json_conf_cmp_(const void *key_, const void *entry_)
{
	const json_conf_entry_ *k_ = (const json_conf_entry_ *)key_;
	const json_conf_entry_ *e_ = (const json_conf_entry_ *)entry_;
	if (k_->len < e_->len) {
		return -1;
	}
	if (k_->len > e_->len) {
		return 1;
	}
	return memcmp(k_->name, e_->name, k_->len);
}
static int json_conf_lookup(const char *str, size_t len)
{
	const json_conf_entry_ key_ = { str, len, 0 };
	const json_conf_entry_ *e_ =
		bsearch(&key_, json_conf_keys_, 21, sizeof(*json_conf_keys_),
			json_conf_cmp_);
	return e_ ? e_->idx : -1;
}

/* --- json_conf_kcp --- */
typedef struct {
	const char *name;
	size_t len;
	int idx;
} json_conf_kcp_entry_;
static const json_conf_kcp_entry_ json_conf_kcp_keys_[] = {
	{ "nc", 2, 3 },	     { "mtu", 3, 2 },	   { "flush", 5, 0 },
	{ "rcvwnd", 6, 5 },  { "resend", 6, 6 },   { "sndwnd", 6, 7 },
	{ "nodelay", 7, 4 }, { "interval", 8, 1 },
};
static int json_conf_kcp_cmp_(const void *key_, const void *entry_)
{
	const json_conf_kcp_entry_ *k_ = (const json_conf_kcp_entry_ *)key_;
	const json_conf_kcp_entry_ *e_ = (const json_conf_kcp_entry_ *)entry_;
	if (k_->len < e_->len) {
		return -1;
	}
	if (k_->len > e_->len) {
		return 1;
	}
	return memcmp(k_->name, e_->name, k_->len);
}
static int json_conf_kcp_lookup(const char *str, size_t len)
{
	const json_conf_kcp_entry_ key_ = { str, len, 0 };
	const json_conf_kcp_entry_ *e_ =
		bsearch(&key_, json_conf_kcp_keys_, 8,
			sizeof(*json_conf_kcp_keys_), json_conf_kcp_cmp_);
	return e_ ? e_->idx : -1;
}

/* --- json_conf_tcp --- */
typedef struct {
	const char *name;
	size_t len;
	int idx;
} json_conf_tcp_entry_;
static const json_conf_tcp_entry_ json_conf_tcp_keys_[] = {
	{ "rcvbuf", 6, 2 },    { "sndbuf", 6, 4 },    { "nodelay", 7, 1 },
	{ "keepalive", 9, 0 }, { "reuseport", 9, 3 },
};
static int json_conf_tcp_cmp_(const void *key_, const void *entry_)
{
	const json_conf_tcp_entry_ *k_ = (const json_conf_tcp_entry_ *)key_;
	const json_conf_tcp_entry_ *e_ = (const json_conf_tcp_entry_ *)entry_;
	if (k_->len < e_->len) {
		return -1;
	}
	if (k_->len > e_->len) {
		return 1;
	}
	return memcmp(k_->name, e_->name, k_->len);
}
static int json_conf_tcp_lookup(const char *str, size_t len)
{
	const json_conf_tcp_entry_ key_ = { str, len, 0 };
	const json_conf_tcp_entry_ *e_ =
		bsearch(&key_, json_conf_tcp_keys_, 5,
			sizeof(*json_conf_tcp_keys_), json_conf_tcp_cmp_);
	return e_ ? e_->idx : -1;
}

/* --- json_conf_udp --- */
static int json_conf_udp_lookup(const char *str, size_t len)
{
	if (len < 2) {
		return -1;
	}
	switch ((unsigned char)str[1]) {
	case 'c':
		return len == 6 && memcmp(str, "rcvbuf", 6) == 0 ? 0 : -1;
	case 'e':
		return len == 9 && memcmp(str, "reuseport", 9) == 0 ? 1 : -1;
	case 'n':
		return len == 6 && memcmp(str, "sndbuf", 6) == 0 ? 2 : -1;
	default:
		return -1;
	}
}

/** @} */

/** @name Key indices
 *  @{ */

enum json_conf_key {
	JSON_CONF_CONNECT = 0,
	JSON_CONF_HTTP_LISTEN = 1,
	JSON_CONF_KCP = 2,
	JSON_CONF_KCP_BIND = 3,
	JSON_CONF_KCP_CONNECT = 4,
	JSON_CONF_KEEPALIVE = 5,
	JSON_CONF_LINGER = 6,
	JSON_CONF_LISTEN = 7,
	JSON_CONF_LOGLEVEL = 8,
	JSON_CONF_METHOD = 9,
	JSON_CONF_NETDEV = 10,
	JSON_CONF_OBFS = 11,
	JSON_CONF_PASSWORD = 12,
	JSON_CONF_PSK = 13,
	JSON_CONF_RENDEZVOUS_SERVER = 14,
	JSON_CONF_SERVICE_ID = 15,
	JSON_CONF_TCP = 16,
	JSON_CONF_TIME_WAIT = 17,
	JSON_CONF_TIMEOUT = 18,
	JSON_CONF_UDP = 19,
	JSON_CONF_USER = 20,
};

enum json_conf_kcp_key {
	JSON_CONF_KCP_FLUSH = 0,
	JSON_CONF_KCP_INTERVAL = 1,
	JSON_CONF_KCP_MTU = 2,
	JSON_CONF_KCP_NC = 3,
	JSON_CONF_KCP_NODELAY = 4,
	JSON_CONF_KCP_RCVWND = 5,
	JSON_CONF_KCP_RESEND = 6,
	JSON_CONF_KCP_SNDWND = 7,
};

enum json_conf_tcp_key {
	JSON_CONF_TCP_KEEPALIVE = 0,
	JSON_CONF_TCP_NODELAY = 1,
	JSON_CONF_TCP_RCVBUF = 2,
	JSON_CONF_TCP_REUSEPORT = 3,
	JSON_CONF_TCP_SNDBUF = 4,
};

enum json_conf_udp_key {
	JSON_CONF_UDP_RCVBUF = 0,
	JSON_CONF_UDP_REUSEPORT = 1,
	JSON_CONF_UDP_SNDBUF = 2,
};

/** @} */

/** @name Free
 *  @{ */

static void json_conf_udp_free(struct json_conf_udp *obj)
{
	(void)obj;
}

static void json_conf_tcp_free(struct json_conf_tcp *obj)
{
	(void)obj;
}

static void json_conf_kcp_free(struct json_conf_kcp *obj)
{
	(void)obj;
}

void json_conf_free(struct json_conf *obj)
{
	json_conf_kcp_free(&obj->kcp);
	json_conf_tcp_free(&obj->tcp);
	json_conf_udp_free(&obj->udp);
}

/** @} */

/** @name Unmarshal
 *  @{ */

static bool
json_conf_udp_unmarshal(struct json_conf_udp *obj, char *json, size_t length)
{
	const struct json_val root_ = json_parse(json, length);
	if (root_.type != JSON_OBJECT) {
		return false;
	}
	json_iter iter_ = root_.iter;
	char *key_;
	size_t key_len_;
	char *val_;
	size_t val_len_;
	while (json_obj_next(
		json, length, &iter_, &key_, &key_len_, &val_, &val_len_)) {
		const int k_ = json_conf_udp_lookup(key_, key_len_);
		switch (k_) {
		case JSON_CONF_UDP_RCVBUF: {
			if (!json_parse_uint(val_, val_len_, &obj->rcvbuf)) {
				return false;
			}
			obj->has_rcvbuf = true;
			break;
		}
		case JSON_CONF_UDP_REUSEPORT: {
			{
				bool bv_;
				if (!json_parse_bool(val_, val_len_, &bv_)) {
					return false;
				}
				obj->reuseport = bv_;
				obj->has_reuseport = true;
			}
			break;
		}
		case JSON_CONF_UDP_SNDBUF: {
			if (!json_parse_uint(val_, val_len_, &obj->sndbuf)) {
				return false;
			}
			obj->has_sndbuf = true;
			break;
		}
		default:
			break;
		}
	}
	return true;
}

static bool
json_conf_tcp_unmarshal(struct json_conf_tcp *obj, char *json, size_t length)
{
	const struct json_val root_ = json_parse(json, length);
	if (root_.type != JSON_OBJECT) {
		return false;
	}
	json_iter iter_ = root_.iter;
	char *key_;
	size_t key_len_;
	char *val_;
	size_t val_len_;
	while (json_obj_next(
		json, length, &iter_, &key_, &key_len_, &val_, &val_len_)) {
		const int k_ = json_conf_tcp_lookup(key_, key_len_);
		switch (k_) {
		case JSON_CONF_TCP_KEEPALIVE: {
			{
				bool bv_;
				if (!json_parse_bool(val_, val_len_, &bv_)) {
					return false;
				}
				obj->keepalive = bv_;
				obj->has_keepalive = true;
			}
			break;
		}
		case JSON_CONF_TCP_NODELAY: {
			{
				bool bv_;
				if (!json_parse_bool(val_, val_len_, &bv_)) {
					return false;
				}
				obj->nodelay = bv_;
				obj->has_nodelay = true;
			}
			break;
		}
		case JSON_CONF_TCP_RCVBUF: {
			if (!json_parse_uint(val_, val_len_, &obj->rcvbuf)) {
				return false;
			}
			obj->has_rcvbuf = true;
			break;
		}
		case JSON_CONF_TCP_REUSEPORT: {
			{
				bool bv_;
				if (!json_parse_bool(val_, val_len_, &bv_)) {
					return false;
				}
				obj->reuseport = bv_;
				obj->has_reuseport = true;
			}
			break;
		}
		case JSON_CONF_TCP_SNDBUF: {
			if (!json_parse_uint(val_, val_len_, &obj->sndbuf)) {
				return false;
			}
			obj->has_sndbuf = true;
			break;
		}
		default:
			break;
		}
	}
	return true;
}

static bool
json_conf_kcp_unmarshal(struct json_conf_kcp *obj, char *json, size_t length)
{
	const struct json_val root_ = json_parse(json, length);
	if (root_.type != JSON_OBJECT) {
		return false;
	}
	json_iter iter_ = root_.iter;
	char *key_;
	size_t key_len_;
	char *val_;
	size_t val_len_;
	while (json_obj_next(
		json, length, &iter_, &key_, &key_len_, &val_, &val_len_)) {
		const int k_ = json_conf_kcp_lookup(key_, key_len_);
		switch (k_) {
		case JSON_CONF_KCP_FLUSH: {
			if (!json_parse_uint(val_, val_len_, &obj->flush)) {
				return false;
			}
			obj->has_flush = true;
			break;
		}
		case JSON_CONF_KCP_INTERVAL: {
			if (!json_parse_uint(val_, val_len_, &obj->interval)) {
				return false;
			}
			obj->has_interval = true;
			break;
		}
		case JSON_CONF_KCP_MTU: {
			if (!json_parse_uint(val_, val_len_, &obj->mtu)) {
				return false;
			}
			obj->has_mtu = true;
			break;
		}
		case JSON_CONF_KCP_NC: {
			if (!json_parse_uint(val_, val_len_, &obj->nc)) {
				return false;
			}
			obj->has_nc = true;
			break;
		}
		case JSON_CONF_KCP_NODELAY: {
			if (!json_parse_uint(val_, val_len_, &obj->nodelay)) {
				return false;
			}
			obj->has_nodelay = true;
			break;
		}
		case JSON_CONF_KCP_RCVWND: {
			if (!json_parse_uint(val_, val_len_, &obj->rcvwnd)) {
				return false;
			}
			obj->has_rcvwnd = true;
			break;
		}
		case JSON_CONF_KCP_RESEND: {
			if (!json_parse_uint(val_, val_len_, &obj->resend)) {
				return false;
			}
			obj->has_resend = true;
			break;
		}
		case JSON_CONF_KCP_SNDWND: {
			if (!json_parse_uint(val_, val_len_, &obj->sndwnd)) {
				return false;
			}
			obj->has_sndwnd = true;
			break;
		}
		default:
			break;
		}
	}
	return true;
}

bool json_conf_unmarshal(struct json_conf *obj, char *json, size_t length)
{
	const struct json_val root_ = json_parse(json, length);
	if (root_.type != JSON_OBJECT) {
		return false;
	}
	json_iter iter_ = root_.iter;
	char *key_;
	size_t key_len_;
	char *val_;
	size_t val_len_;
	while (json_obj_next(
		json, length, &iter_, &key_, &key_len_, &val_, &val_len_)) {
		const int k_ = json_conf_lookup(key_, key_len_);
		switch (k_) {
		case JSON_CONF_CONNECT: {
			if (!json_parse_string(
				    val_, val_len_, &obj->connect,
				    &obj->connect_len)) {
				return false;
			}
			break;
		}
		case JSON_CONF_HTTP_LISTEN: {
			if (!json_parse_string(
				    val_, val_len_, &obj->http_listen,
				    &obj->http_listen_len)) {
				return false;
			}
			break;
		}
		case JSON_CONF_KCP: {
			if (!json_conf_kcp_unmarshal(
				    &obj->kcp, val_, val_len_)) {
				return false;
			}
			obj->has_kcp = true;
			break;
		}
		case JSON_CONF_KCP_BIND: {
			if (!json_parse_string(
				    val_, val_len_, &obj->kcp_bind,
				    &obj->kcp_bind_len)) {
				return false;
			}
			break;
		}
		case JSON_CONF_KCP_CONNECT: {
			if (!json_parse_string(
				    val_, val_len_, &obj->kcp_connect,
				    &obj->kcp_connect_len)) {
				return false;
			}
			break;
		}
		case JSON_CONF_KEEPALIVE: {
			if (!json_parse_uint(val_, val_len_, &obj->keepalive)) {
				return false;
			}
			obj->has_keepalive = true;
			break;
		}
		case JSON_CONF_LINGER: {
			if (!json_parse_uint(val_, val_len_, &obj->linger)) {
				return false;
			}
			obj->has_linger = true;
			break;
		}
		case JSON_CONF_LISTEN: {
			if (!json_parse_string(
				    val_, val_len_, &obj->listen,
				    &obj->listen_len)) {
				return false;
			}
			break;
		}
		case JSON_CONF_LOGLEVEL: {
			if (!json_parse_uint(val_, val_len_, &obj->loglevel)) {
				return false;
			}
			obj->has_loglevel = true;
			break;
		}
		case JSON_CONF_METHOD: {
			if (!json_parse_string(
				    val_, val_len_, &obj->method,
				    &obj->method_len)) {
				return false;
			}
			break;
		}
		case JSON_CONF_NETDEV: {
			if (!json_parse_string(
				    val_, val_len_, &obj->netdev,
				    &obj->netdev_len)) {
				return false;
			}
			break;
		}
		case JSON_CONF_OBFS: {
			if (!json_parse_string(
				    val_, val_len_, &obj->obfs,
				    &obj->obfs_len)) {
				return false;
			}
			break;
		}
		case JSON_CONF_PASSWORD: {
			if (!json_parse_string(
				    val_, val_len_, &obj->password,
				    &obj->password_len)) {
				return false;
			}
			break;
		}
		case JSON_CONF_PSK: {
			if (!json_parse_string(
				    val_, val_len_, &obj->psk, &obj->psk_len)) {
				return false;
			}
			break;
		}
		case JSON_CONF_RENDEZVOUS_SERVER: {
			if (!json_parse_string(
				    val_, val_len_, &obj->rendezvous_server,
				    &obj->rendezvous_server_len)) {
				return false;
			}
			break;
		}
		case JSON_CONF_SERVICE_ID: {
			if (!json_parse_string(
				    val_, val_len_, &obj->service_id,
				    &obj->service_id_len)) {
				return false;
			}
			break;
		}
		case JSON_CONF_TCP: {
			if (!json_conf_tcp_unmarshal(
				    &obj->tcp, val_, val_len_)) {
				return false;
			}
			obj->has_tcp = true;
			break;
		}
		case JSON_CONF_TIME_WAIT: {
			if (!json_parse_uint(val_, val_len_, &obj->time_wait)) {
				return false;
			}
			obj->has_time_wait = true;
			break;
		}
		case JSON_CONF_TIMEOUT: {
			if (!json_parse_uint(val_, val_len_, &obj->timeout)) {
				return false;
			}
			obj->has_timeout = true;
			break;
		}
		case JSON_CONF_UDP: {
			if (!json_conf_udp_unmarshal(
				    &obj->udp, val_, val_len_)) {
				return false;
			}
			obj->has_udp = true;
			break;
		}
		case JSON_CONF_USER: {
			if (!json_parse_string(
				    val_, val_len_, &obj->user,
				    &obj->user_len)) {
				return false;
			}
			break;
		}
		default:
			break;
		}
	}
	return true;
}

/** @} */
